name: Check
on: push
jobs:
  lint:
    runs-on: Windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3
          - name:Install deps
          run:npm ci
          -name:Lint
          run:npm run lint
          
