name: Workflow_Demo
on: push
jobs:
 test:
    runs-on: windows-latest
    steps:
      - name: Get repossitory code
        uses: actions/checkout@v4
      
      - name: Test application
        run: dotnet test

