name: Workflow_Demo
on: push
jobs:
 test:
    runs-on: windows-latest
    steps:
      - name: Set up dotnet
        uses: actions/checkout@v4
        with: 
          dotnet-version: '8.0.204'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with dotnet CLI
        run: dotnet test
      
      

