name: Workflow_Demo
on: push
jobs:
 test:
    runs-on: windows-latest
    steps:
      - name: Get repossitory code
        uses: actions/checkout@v4
      - name: Instal dependecies 
        run: npm install
      - name: Test application
        run: npm run test

